# Generated by Django 4.2.15 on 2024-09-05 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tincture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('herbs', models.CharField(max_length=100)),
                ('solvent', models.CharField(max_length=100)),
            ],
        ),
    ]
