# Generated by Django 4.2.15 on 2024-09-10 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_herb_remove_tincture_herbs_tincture_herbs'),
    ]

    operations = [
        migrations.AddField(
            model_name='herb',
            name='material',
            field=models.CharField(choices=[('L', 'Leaf'), ('F', 'Flower'), ('R', 'Root'), ('B', 'Bark'), ('E', 'Berry')], default='L', max_length=1),
        ),
        migrations.AddField(
            model_name='herb',
            name='state',
            field=models.CharField(choices=[('F', 'Fresh'), ('D', 'Dried')], default='F', max_length=1),
        ),
    ]
