# Generated by Django 4.2.15 on 2024-09-10 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_batch'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batch',
            options={'ordering': ['-prep_date']},
        ),
    ]
