# Generated by Django 4.2.15 on 2024-09-10 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_batch_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tincture',
            name='herbs',
        ),
        migrations.AddField(
            model_name='herb',
            name='tinctures',
            field=models.ManyToManyField(to='main_app.tincture'),
        ),
    ]
