# Generated by Django 4.2.15 on 2024-09-10 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_remove_tincture_herbs_herb_tinctures'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='herb',
            name='tinctures',
        ),
        migrations.AddField(
            model_name='tincture',
            name='herbs',
            field=models.ManyToManyField(to='main_app.herb'),
        ),
    ]
