# Generated by Django 4.2.15 on 2024-09-11 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_remove_herb_tinctures_tincture_herbs'),
    ]

    operations = [
        migrations.AddField(
            model_name='tincture',
            name='image',
            field=models.CharField(default='https://imgur.com/a/ygqWMRm', max_length=100),
        ),
    ]
