# Generated by Django 4.2.15 on 2024-09-13 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_alter_tincture_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tincture',
            name='image',
            field=models.CharField(default='https://i.postimg.cc/T3hVGrk7/Default.jpg', max_length=100),
        ),
    ]
