# Generated by Django 4.2.15 on 2024-09-14 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_alter_tincture_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='herb',
            name='image',
            field=models.CharField(default='https://i.postimg.cc/0NQ0ty2L/65411-E92-1783-46-D3-907-F-7-FA037834-E9-E.jpg', max_length=100),
        ),
    ]
